#!/bin/bash

python scripts/preprocess.py --input_path /data/iemanja/rave_trn --output_path ./runs/dataset --channels 1 --sampling_rate 16000 --ext wav

python scripts/train.py --config ./configs/cls.gin --db_path ./runs/dataset/ --out_path ./runs/models/ch10 --name iemenja --gpu 0 --channels 1 --save_every 11000 --batch 32 --max_steps 55000








# python scripts/preprocess.py --input_path /data/rave_trn --output_path ./runs/dataset --channels 1 --sampling_rate 16000 --ext wav

# cd ./runs/models/cls_10
# tensorboard --logdir . --port 8888 --bind_all &

# cd ../../..

# python scripts/train.py --config ./configs/cls_10.gin --db_path ./runs/dataset/ --out_path ./runs/models/cls_10 --name iemenja --gpu 0 --channels 1 --save_every 100000 --batch 64 --max_steps 6000000

# python scripts/export.py --run ./runs/runs/models/cls_10/cls_0_f643bacf96/ --name cls_10_95 --output ./runs/exported_models --fidelity 0.95
# python scripts/export.py --run ./runs/runs/models/cls_10/cls_0_f643bacf96/ --name cls_10_99 --output ./runs/exported_models --fidelity 0.99
